### ISSUE TITLE
这个水印什么情况下攻击会成功?

### ISSUE THREAD

**Issue by banduoba** [guofei9987/blind_watermark#1]
你好,使用这个添加水印之后,通过什么样子的方式攻击会破坏水印呢

**Comment by guofei9987** [comment]
手机拍屏

**Comment by xwu6614555** [comment]
> 手机拍屏

您好，手机拍屏不破坏水印，有什么思路吗？谢谢！

**Comment by guofei9987** [comment]
> > 手机拍屏
> 
> 您好，手机拍屏不破坏水印，有什么思路吗？谢谢！

有，大杀器不开源

**Comment by banduoba** [comment]
> > > 手机拍屏
> > 
> > 
> > 您好，手机拍屏不破坏水印，有什么思路吗？谢谢！
> 
> 有，大杀器不开源

有视频什么的看下么,也是抗攻击的数字水印么
