### ISSUE TITLE
在特征值上添加水印和提取水印的函数

### ISSUE THREAD

**Issue by suancaizxt** [guofei9987/blind_watermark#10]
非常有用，效果感觉很不错！
有一处细节请教下：
https://github.com/guofei9987/blind_watermark/blob/88ba12394edef0cb4905148743809dcfa500812a/blind_watermark/blind_watermark.py#L85
这里为什么用这种函数关系来添加水印？有什么理论指导吗？

**Comment by guofei9987** [comment]
> 非常有用，效果感觉很不错！
> 有一处细节请教下：
> https://github.com/guofei9987/blind_watermark/blob/88ba12394edef0cb4905148743809dcfa500812a/blind_watermark/blind_watermark.py#L85
> 
> 
> 这里为什么用这种函数关系来添加水印？有什么理论指导吗？

本质上是均匀地映射到最近地离散点上

**Comment by suancaizxt** [comment]
嗯，谢谢回复，明白了
