### ISSUE TITLE
选择多进程mode, 无法运行报下面的错误

### ISSUE THREAD

**Issue by wangyue168git** [guofei9987/blind_watermark#102]
NotImplementedError: pool objects cannot be passed between processes or pickled

环境：mac OS

**Comment by guofei9987** [comment]
It seems work well on my macOS and Linux. 
See this: https://github.com/guofei9987/blind_watermark/blob/master/examples/example_str_multi.py

Pls show me your code and environments.

**Comment by liduang** [comment]
不对吧，你这个example_str_nulti的传参都错了，processes='multiprocessing'？不应该是mode='multiprocessing'吗？

**Comment by ttbuffey** [comment]
I also has this issue, how you fix? @liduang

**Comment by ttbuffey** [comment]
@guofei9987 how to fix this issue, i also get this error
