### ISSUE TITLE
截图图片必须跟原图尺寸大小一样才能解码成功

### ISSUE THREAD

**Issue by goal-Qinxin** [guofei9987/blind_watermark#108]
能否支持截图尺寸跟原图不一致，也能解码？

**Comment by lambdaq** [comment]
目测不能。

**Comment by guofei9987** [comment]
可以，但需要知道裁剪位置和缩放比例。

一个方案是使用原图来计算这些参数，参考：https://github.com/guofei9987/blind_watermark/blob/1e494d89332da194dd1f1723209f0e66270fcc67/examples/example_str.py#L51

**Comment by lambdaq** [comment]
@guofei9987  我自己测了下，如果缩小，再按原尺寸还原，文字出现部分乱码。感觉还是有部分信息丢失或者乱了。这种情况是不是要用一些 error correction 技术才能保证信息能100%还原？
