### ISSUE TITLE
增加水印后，图像的质量下降了

### ISSUE THREAD

**Issue by kitcheng** [guofei9987/blind_watermark#109]
无论是添加图片水印还是文字水印，添加之后对比原图，质量都下降了很多，而且体积也小了很多，这个是使用的问题呢还是算法的问题呢？

**Comment by guofei9987** [comment]
大概率是三维的图像矩阵保存为图片文件时的参数问题，可以参考：

https://github.com/guofei9987/blind_watermark/blob/master/examples/example_no_writing.py

上面的代码直接操作图像对应的三维矩阵。你需要在它的基础上自己写保存图片的代码，以保存为需要的最佳图片。
