### ISSUE TITLE
亮度攻击抵抗力较差

### ISSUE THREAD

**Issue by suancaizxt** [guofei9987/blind_watermark#11]
这里我做了一下小改动：
https://github.com/guofei9987/blind_watermark/blob/88ba12394edef0cb4905148743809dcfa500812a/blind_watermark/blind_watermark.py#L154
本质上是对每个block按bit打上的水印，这里也把每个block提取到的水印由浮点数转为0和1：
`wm[i] = (wm_extract[:, i::self.wm_size].mean()>0.5)*1`
然后可以将提取到的水印和原始水印做同或得到误码率来评价抗攻击的效果。
最后结论是亮度调低10%攻击下误码率就已达到29%...对比之下裁剪50%和缩放50%下误码率分别是2%和1%。
其实也可以理解，水印嵌在图像的中低频，亮度攻击正是改变了图像的中低频（然而调亮度往往是最常见的修改，比如美图秀秀加个滤镜拉下曝光...）。
不知道po主有无更好的方案，在不改变（或尽量少改变）图像画质的前提下，获得更好的抗亮度攻击的方案呢？或有相关领域的paper可以推荐？

**Comment by guofei9987** [comment]
👍
确实是个问题，容我调研一下

**Comment by suancaizxt** [comment]
嗯嗯 持续关注中

**Comment by suancaizxt** [comment]
找到了一种基于差分编码的方法，感觉挺有效，来跟po主讨论下:)
[https://www.researchgate.net/publication/280873467_Blind_image_watermarking_technique_based_on_differential_embedding_in_DWT_and_DCT_domains](url)
基本思路是将图像小波变换后，zigzag均分成两个等长的部分，根据经验，这两个部分的相关性很高，所以DCT系数是基本相等的。利用这个性质可以在把watermark以差分的形式打到两个DCT序列的相同索引。这种方式对图像造成的影响很小（尤其是平坦区），而且对亮度变化是鲁棒的。
原文是在全图尺寸做变换和打水印，DWT和DCT的运算成本都太大了。基于po主的代码可以很方便把文中的思想按8*8的block的实现，而且效果还不错。
结论如下：

1. 对画质损伤小，PSNR一般在40dB以上。尤其是对平坦区的影响很小，因此，即便是在相同PSNR下，肉眼画质损伤情况也要小于po主的方式
2. 对裁剪、亮度变换是鲁棒的
3. 完全不抗模糊、压缩、scale等损失高频的攻击
可见这个方式跟po主的方法刚好是互补的，po主的方法能扛得住高频攻击，但扛不住低频攻击，另外画质损伤（尤其平坦区）较为严重。我这里后来将po主的方式和上面的方式做到了一起，相当于给图像打了两层水印，效果还可以，po主可以尝试一下哈~

如果po主有更好的方式，欢迎继续交流：）

**Comment by BertChenJames** [comment]
> DCT
请问有开源代码吗？
