### ISSUE TITLE
解码时乱码，数字也乱码

### ISSUE THREAD

**Issue by mikemhm** [guofei9987/blind_watermark#111]
![image](https://github.com/guofei9987/blind_watermark/assets/52308569/025cfbcb-425d-4c56-a30e-9c3de331dc8f)

**Comment by zhuxinjin** [comment]
解码时把 --wm_shape 后面的值111 改成 Put down watermark size的值 22

**Comment by a410202049** [comment]
那这样的话 截图攻击 这个水映 就变得毫无意义

**Comment by asuratu** [comment]
> 那这样的话 截图攻击 这个水映 就变得毫无意义

是的, 截图还是会乱码
