### ISSUE TITLE
这个项目真的很好，不知道能不能打包成exe文件呢？想用GUI桌面工具来调用这个批量给图片添加水印

### ISSUE THREAD

**Issue by hzdlive** [guofei9987/blind_watermark#120]
这个项目真的很好，不知道能不能打包成exe文件呢？想用GUI桌面工具来调用这个批量给图片添加水印

**Comment by guofei9987** [comment]
这个项目不直接面向消费者。GUI之类的可以基于这个项目封装一下，或者用 Django 之类基于网页做交互界面
