### ISSUE TITLE
剪切攻击 + 缩放攻击 + 不知道攻击参数 能否在没有原始的加完水印后的图的时候提取参数

### ISSUE THREAD

**Issue by sheiy** [guofei9987/blind_watermark#125]
<img width="981" alt="image" src="https://github.com/guofei9987/blind_watermark/assets/12210038/8ace41ff-1159-42cc-8a18-f4d4d88c95df">

**Comment by guofei9987** [comment]
使用原始图片是为了寻找水印二进制的起始位置。
其实可以不用原始图片的，没开源

**Comment by sheiy** [comment]
是要收费吗？还是有开源的计划？
@guofei9987

**Comment by guofei9987** [comment]
> 是要收费吗？还是有开源的计划？ @guofei9987

目前还没有开源的计划，也不会拿出来卖

**Comment by zhLawliet** [comment]
@guofei9987 请问下，是不是给水印加一个位置信息就可以不用原图了？只是这个位置信息可能会被损害
