### ISSUE TITLE
解码需要提供wm_shape这个参数，正确的使用方法是怎样的？谢谢

### ISSUE THREAD

**Issue by schonglin** [guofei9987/blind_watermark#126]
解析水印 需要用到原图加水印返回的size。
比如现在用户跟很多图片添加了水印，并且水印码都不一样，那么返回的size也是不一样的，现在用户随便拿一张添加了水印的图片来解码水印，难不成还要提供这张图加水印时候返回的size，是需要每一张图加水印的时候都要记录这个size吗？谢谢

**Comment by guofei9987** [comment]
统一规定一个长度就行了。长度不够的补0

**Comment by schonglin** [comment]
统一规定一个长度？ 能提供一个demo示例吗 谢谢

**Comment by schonglin** [comment]
查看帮助命令 没有看到有固定长度的参数 希望抽出你宝贵的时间 指点一下 谢谢
![_MGX`JX~QG7K 403)YZ$U~V](https://github.com/guofei9987/blind_watermark/assets/29223707/a491d7c9-3bf0-4611-a048-d3420705d5f5)

**Comment by schonglin** [comment]
已搞定 谢谢

**Comment by rwqzcq** [comment]
> 已搞定 谢谢

请问您是怎么解决的这个问题？

**Comment by jdfgfcvb** [comment]
> 已搞定 谢谢

大佬，请问是怎么解决这个问题的，能分享一下经验吗？
