### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by seamusopen** [guofei9987/blind_watermark#19]
使用阿里的镜像源，没有找到这个包
ERROR: No matching distribution found for blind-watermark

**Comment by guofei9987** [comment]
更建议使用 pypi 的官方源呢 https://pypi.org/project/blind-watermark/，其他源可能同步不及时或者不稳定。
我看清华源是有的 https://pypi.tuna.tsinghua.edu.cn/simple/blind-watermark/
