### ISSUE TITLE
图片裁剪了中间区域如何得到水印？

### ISSUE THREAD

**Issue by KrioWly** [guofei9987/blind_watermark#2]
如果图片随机裁剪了图片的中间区域，你并不知道被裁减了多少，请问这种如何得到复原的水印？

**Comment by guofei9987** [comment]
现在的代码还不支持，手里有个调整方案，但不支持加密。再研究一段时间后再更新进去。

**Comment by HZB8080** [comment]
大佬。请问有没更新了裁剪验证的功能

**Comment by andyhewenhui** [comment]
裁剪复原可以支持就完美了

**Comment by guofei9987** [comment]
v0.2.1 版本已支持裁剪任意中间区域

**Comment by andyhewenhui** [comment]
> v0.2.1 版本已支持裁剪任意中间区域
> 
> https://github.com/guofei9987/blind_watermark/blob/9d0acdb8593e99d631858ae0e04702f2c6bd5890/examples/str_att.py#L23

great!!!
