### ISSUE TITLE
经常遇到这个问题 AssertionError: 最多可嵌入10.88kb信息，多于水印的50.445kb信息，溢出

### ISSUE THREAD

**Issue by ikalista** [guofei9987/blind_watermark#20]
这个信息量是受制于水印的大小还是其他原因呢
我更换了更小的水印依然会出现这个问题（比项目中的二维码还小）
![image](https://user-images.githubusercontent.com/35593733/113476957-5cae9680-94b1-11eb-882e-84abfb969c3e.png)

**Comment by guofei9987** [comment]
原图和水印分辨率的比例最低是16:1

**Comment by ikalista** [comment]
> 原图和水印分辨率的比例最低是16:1
谢谢大佬回复！
抱歉原来是我没有设置水印的shape的问题，这样就正常了，我就发一下给也许会遇到这个问题的朋友们
![image](https://user-images.githubusercontent.com/35593733/113505650-ca6ec700-9572-11eb-828e-6158ecc33377.png)

**Comment by github-luffy** [comment]
为啥原图和水印 不能同比例
