### ISSUE TITLE
feature request:  execute in shell

### ISSUE THREAD

**Issue by jayagami** [guofei9987/blind_watermark#21]
execute command in shell directly without create a new python script

**Comment by guofei9987** [comment]
👌

**Comment by guofei9987** [comment]
I forgot that the command shell is already there

```
cd examples
python 命令行.py 
```

**Comment by jayagami** [comment]
> I forgot that the command in shell is already there.
> 
> ```
> cd examples
> python 命令行.py 
> ```

Thanks for replying,   examples you mentioned should be fine.
what I am trying to say is adding an `entry_points` in step script.

**Comment by guofei9987** [comment]
It is available in version 0.1.1

https://github.com/guofei9987/blind_watermark#use-in-bash
