### ISSUE TITLE
原图是不是满足什么样的条件才可以识别出暗码？我电脑截屏了一个图片无法识别出暗码

### ISSUE THREAD

**Issue by huoweian** [guofei9987/blind_watermark#22]

**Comment by guofei9987** [comment]
大多数能识别的。

如果图片大部分在低频区域，算法需要调参。相关方法我已经写好了（虽然还比较粗糙，有空再优化）`bwm.extract_raw`

**Comment by andyhewenhui** [comment]
截图的方式也解决了？

**Comment by Vickko** [comment]
截屏攻击确实无法识别。

我在m1 MacBook，macos11.3上尝试了readme内的样例图片，具体方式为使用原图和水印生成embedded.png后，使用系统自带的预览app打开，放大至全屏并截屏。生成新的screenshot图片后尝试extract，生成噪声图片，无法识别。
![exscreenshot](https://user-images.githubusercontent.com/54114807/117561293-325f8280-b0c8-11eb-8974-66e57a5fab2d.png)

![ori_img](https://user-images.githubusercontent.com/54114807/117561250-a0577a00-b0c7-11eb-8883-9a615acac400.jpg)
![watermark](https://user-images.githubusercontent.com/54114807/117561253-ad746900-b0c7-11eb-8273-1d3b79ed433a.png)
![embedded](https://user-images.githubusercontent.com/54114807/117561257-b5340d80-b0c7-11eb-98bd-7b70d0524177.png)
![screenshot](https://user-images.githubusercontent.com/54114807/117561283-fe845d00-b0c7-11eb-9248-21ecdd55c803.jpg)

**Comment by warm-ice0x00** [comment]
截图用 PIL resize 到原图尺寸就可以识别了。

**Comment by guofei9987** [comment]
最近更新了一个版本，对截屏攻击的抵抗力大大增强，见于这里：
https://github.com/guofei9987/blind_watermark/blob/4c52b9a71895763748c9d4cfefc837db715a32a4/examples/example_str.py#L40
