### ISSUE TITLE
压缩的图片不支持？

### ISSUE THREAD

**Issue by huoweian** [guofei9987/blind_watermark#23]

**Comment by guofei9987** [comment]
支持的

**Comment by huoweian** [comment]
你好，我刚刚尝试了通过微信不发送原图的方式去发送一个带盲水印的图片，然后解码不出来水印

**Comment by guofei9987** [comment]
我测过可以的。把你的图片/水印格式、参数发一下我测一下看看？

**Comment by huoweian** [comment]
#

> 我测过可以的。把你的图片/水印格式、参数发一下我测一下看看？

这是代码
`from blind_watermark import WaterMark

bwm1 = WaterMark(password_wm=1, password_img=1)
bwm1.extract(filename="output/压缩.jpeg", wm_shape=(128, 128), out_wm_name="output/压缩_提取水印.jpeg")`

![压缩](https://user-images.githubusercontent.com/17921193/114336929-a585df80-9b82-11eb-9138-3ab22b1877ec.jpeg)

**Comment by 10wei1000** [comment]
今天遇到了同样的问题。微信压缩后图片尺寸变小了，自己用opencv还原到了原图尺寸，可是还是无法提取出水印。不知道是哪里没做对，请大佬赐教！
