### ISSUE TITLE
对Mark.png 的大小有限制吗？

### ISSUE THREAD

**Issue by Zforw** [guofei9987/blind_watermark#24]
运行的时候报错：
assert self.wm_size < self.block_num, IndexError(
AssertionError: 最多可嵌入81.0kb信息，多于水印的750.519kb信息，溢出

**Comment by Zforw** [comment]
我mark.png 都12kb了还不行...

**Comment by guofei9987** [comment]
这个信息量是按照像素个数计算的。原图：水印>16:1 即可
