### ISSUE TITLE
如何自证是加了水印的呢？

### ISSUE THREAD

**Issue by Famine-Life** [guofei9987/blind_watermark#25]
我看您的示例图片，貌似没有在图片内显示水印。

能不能做到解水印操作完成就直接在图片上显示出来。类似：

https://pic2.zhimg.com/v2-fe1371c04d3655695a87042775bc574d_r.jpg

**Comment by guofei9987** [comment]
这个库是做隐水印的，不是做显水印的。

显水印比较简单，不需要库，用 $a*p1+(1-a)*p2$  就能简单实现
