### ISSUE TITLE
剪裁之后解不出来 水印

### ISSUE THREAD

**Issue by 0FuzzingQ** [guofei9987/blind_watermark#27]
你好 我在使用代码进行图片水印嵌入的时候 在测试 剪裁后提取信息时遇到了问题 请问下是我的代码哪里有问题吗？

源图片：
![target_color](https://user-images.githubusercontent.com/27672638/116516807-a481db80-a900-11eb-96ba-ea9cbf216080.png)
水印图片：
![wm2](https://user-images.githubusercontent.com/27672638/116516838-b06d9d80-a900-11eb-8f04-ce66011992d4.png)

代码：
```
from blind_watermark import WaterMark

bwm1 = WaterMark(password_wm=1, password_img=1)
# read original image
bwm1.read_img('target_color.png')
# read watermark
bwm1.read_wm('wm2.png')
# embed
bwm1.embed('output_color.png')
```

将获取的 output_color.png 剪裁为 如下：
![output_color](https://user-images.githubusercontent.com/27672638/116517035-f296df00-a900-11eb-8488-a66dd1a4a89c.png)

再通过以下代码提取信息 ：
```
bwm1 = WaterMark(password_wm=1, password_img=1)
bwm1.extract(filename='output_color.png', wm_shape=(60, 60), out_wm_name='extracted_color_cut.png', )
```

提取说出来的信息已经变成无法识别了：
![extracted_color_cut](https://user-images.githubusercontent.com/27672638/116517125-13f7cb00-a901-11eb-95ac-29c32d27f5c2.png)

**Comment by p1slave** [comment]
我也遇到这个问题了，你解决了吗？

**Comment by guofei9987** [comment]
> 我也遇到这个问题了，你解决了吗？

https://github.com/guofei9987/blind_watermark/blob/0764d035fa5acdbc82c4e74e562b575a6e9421c0/examples/example_str.py#L40
