### ISSUE TITLE
提取文字水印的时候省略wm_shape是否可行

### ISSUE THREAD

**Issue by gbcdef** [guofei9987/blind_watermark#28]
这段提取文字水印的代码需要基于加水印时的`len_wm = len(bwm1.wm_bit)`，那就得先知道文字水印是什么才可以提取。不知道在原理上是否可以省略提取文字水印时的wm_shape这个值？

```
bwm1 = WaterMark(password_img=1, password_wm=1)
wm_extract = bwm1.extract('output/embedded.png', wm_shape=len_wm, mode='str')
print(wm_extract)
```

**Comment by guofei9987** [comment]
需要知道水印的长度才能提取，这也算一种变相的加密了

**Comment by gbcdef** [comment]
> 需要知道水印的长度才能提取，这也算一种变相的加密了

研究了一下计算wm_bit的地方，因为用的是utf-8变长的编码，所以这里是不是基本等同于需要文字水印的原文才能提取原文了？感觉好像开始套娃了-.-

```
        elif mode == 'str':
            byte = bin(int(wm_content.encode('utf-8').hex(), base=16))[2:]
            self.wm_bit = (np.array(list(byte)) == '1')
```

**Comment by guofei9987** [comment]
> > 需要知道水印的长度才能提取，这也算一种变相的加密了
> 
> 研究了一下计算wm_bit的地方，因为用的是utf-8变长的编码，所以这里是不是基本等同于需要文字水印的原文才能提取原文了？感觉好像开始套娃了-.-
> 
> ```
>         elif mode == 'str':
>             byte = bin(int(wm_content.encode('utf-8').hex(), base=16))[2:]
>             self.wm_bit = (np.array(list(byte)) == '1')
> ```

提供了嵌入二进制的方法 `mode='bit'`，可以自定义编码到二进制

**Comment by gbcdef** [comment]
> > > 需要知道水印的长度才能提取，这也算一种变相的加密了
> > 
> > 
> > 研究了一下计算wm_bit的地方，因为用的是utf-8变长的编码，所以这里是不是基本等同于需要文字水印的原文才能提取原文了？感觉好像开始套娃了-.-
> > ```
> >         elif mode == 'str':
> >             byte = bin(int(wm_content.encode('utf-8').hex(), base=16))[2:]
> >             self.wm_bit = (np.array(list(byte)) == '1')
> > ```
> 
> 提供了嵌入二进制的方法 `mode='bit'`，可以自定义编码到二进制

套娃的问题我想通了，可以在生成文字水印的时候把长度算出来存下，password_wm+password_img+wm_bit_length作为密码。可以不用提供原文了。
