### ISSUE TITLE
jpeg

### ISSUE THREAD

**Issue by edwardocano** [guofei9987/blind_watermark#3]
Hi! the watermark disappear with jpeg compression. Do you have any idea how to solve it?

**Comment by guofei9987** [comment]
Jpeg compression works well  in my computer. Would you pls try again or show me your code?

**Comment by edwardocano** [comment]
Sorry my fault. How can i know what is the smalles image i can embed?

**Comment by guofei9987** [comment]
The smallest size of embedded message is size of origin image divided by 16
