### ISSUE TITLE
大佬，做了攻击之后还是需要原图大小才能提取水印？

### ISSUE THREAD

**Issue by BertChenJames** [guofei9987/blind_watermark#30]
大佬，请教一下！
比如说对图片进行裁剪，裁剪成原来的1/2，如果不还原成原图大小，那么 这样提取出的水印就是错的，所以说在受到不同攻击后，还是需要原图的大小才能提取出水印，请问怎么解决这个问题呢？
还有若是做了旋转攻击，需要知道旋转角度，进行还原，才能提取出水印，在日常中我们不知道受到了怎样的攻击，这个问题咋解决呢？
请大佬指教一下，谢谢🙏

**Comment by guofei9987** [comment]
你肯定知道自己的原图，跟原图对比一下就知道如何还原了
