### ISSUE TITLE
拍照之后可以提取吗？

### ISSUE THREAD

**Issue by creboy** [guofei9987/blind_watermark#31]
![2](https://user-images.githubusercontent.com/27350646/118585114-d59c5000-b7ca-11eb-9695-4d718ecc5eed.jpg)

![344](https://user-images.githubusercontent.com/27350646/118585139-de8d2180-b7ca-11eb-9c75-59d807111c86.jpg)

from blind_watermark import WaterMark

bwm1 = WaterMark(password_img=1, password_wm=1)
bwm1.read_img('2.jpg')
wm = '@guofei9987 开源万岁！'
bwm1.read_wm(wm, mode='str')
bwm1.embed('embedded.png')
len_wm = len(bwm1.wm_bit)
print('Put down the length of wm_bit {len_wm}'.format(len_wm=len_wm))

bwm1 = WaterMark(password_img=1, password_wm=1)
wm_extract = bwm1.extract('344.jpg', wm_shape=len_wm, mode='str')
print(wm_extract)

Traceback (most recent call last):
  File "C:\Users\yu\Desktop\pic\1.py", line 12, in <module>
    wm_extract = bwm1.extract('344.jpg', wm_shape=len_wm, mode='str')
  File "C:\Users\yu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\blind_watermark\blind_watermark.py", line 165, in extract
    wm = bytes.fromhex(hex(int(byte, base=2))[2:]).decode('utf-8')
ValueError: non-hexadecimal number found in fromhex() arg at position 1
>>>

**Comment by guofei9987** [comment]
不能
