### ISSUE TITLE
我有个9856*1400的图片可以嵌入水印，但抗攻击性非常差

### ISSUE THREAD

**Issue by ytfrdfiw** [guofei9987/blind_watermark#32]
如题，稍微抠一点内容就会报如下异常：
imgcodecs\src\loadsave.cpp:738: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
但代码中提供的图片，或我自己小点的图片，是可以嵌入与提取的，且抗攻击性不错。
不知道作者是否能提供新的解决方法，感谢！

**Comment by guofei9987** [comment]
如果被嵌入的图片低频区域较多，需要把阈值从0.5改小。  

`mode='bit'` ，解密出来的二进制每一位都是0-1之间的float，而不是0/1 二值型。

画一下分布图，观察最适合的阈值，手动改小。

**Comment by guofei9987** [comment]
最新的 v0.2.1 版本对抗攻击性做了极大的提升
