### ISSUE TITLE
请问有这个算法的步骤详解吗

### ISSUE THREAD

**Issue by WayoSunny** [guofei9987/blind_watermark#35]
请问是否有相关文档描述该算法？（除了看源码）

**Comment by guofei9987** [comment]
去 Google Scholar 上搜一下 blind watermark dct，这个库是基于几个相关论文做的

**Comment by WayoSunny** [comment]
好的！感谢！

在 2021-06-12 15:32:01，"郭飞" ***@***.***> 写道：

去 Google Scholar 上搜一下 blind watermark dct，这个库是基于几个相关论文做的
