### ISSUE TITLE
图片质量下降

### ISSUE THREAD

**Issue by yhl41001** [guofei9987/blind_watermark#4]
加水印的一个难题是对源图片的质量破坏，从例子来看，对图片的破坏，还是有点严重，有继续研究对图片质量影响更低的加水印方法吗？

**Comment by guofei9987** [comment]
现在的效果也还凑合吧，裁切一半后的二维码也能还原出来。如果想要更加抗攻击，需要对图片做针对性的调参。或者增加冗余。
