### ISSUE TITLE
加水印后图片质量降低了不少

### ISSUE THREAD

**Issue by starinskycc** [guofei9987/blind_watermark#42]
测试图片
https://big.justeasy.cn/large/202108/20210824083411_61243e83f2731.jpg
测试水印
https://res1.justeasy.cn/images/new/ewm.png
结果图
https://big.justeasy.cn/cctest.jpg

另外打水印的时间1-2秒，能不能给优化一下，机器配置 4C 8G

**Comment by starinskycc** [comment]
好像CDN那边有REFERER过滤，复制就可以打开了

**Comment by guofei9987** [comment]
测试水印可以打开，另外两个图打不开
