### ISSUE TITLE
是否考虑直接对字符串进行编解码而不是以图藏图呢？前者感觉更简单更实用一些

### ISSUE THREAD

**Issue by RGBli** [guofei9987/blind_watermark#44]

**Comment by guofei9987** [comment]
本就有此功能
- 藏字符串 ：https://github.com/guofei9987/blind_watermark/blob/master/examples/origin_str.py
- 藏二进制：https://github.com/guofei9987/blind_watermark/blob/master/examples/origin_bit.py

**Comment by RGBli** [comment]
是我疏忽了，没有看到，为你点赞！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guofei9987/blind_watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guofei9987/blind_watermark] 是否考虑直接对字符串进行编解码而不是以图藏图呢？前者感觉更简单更实用一些 (#44)





 
本就有此功能
  
藏字符串 ：https://github.com/guofei9987/blind_watermark/blob/master/examples/origin_str.py
 
藏二进制：https://github.com/guofei9987/blind_watermark/blob/master/examples/origin_bit.py
