### ISSUE TITLE
请问图片要大于多少象素，才可以？

### ISSUE THREAD

**Issue by cliffcrag** [guofei9987/blind_watermark#53]
我看了：ori_img.jpg 图是 1920X1200象素，但是我有个图是1080X608,水印同样是128X128象素的。就不行了。就会有如下提示：

_File "D:\program\Anaconda3\lib\site-packages\blind_watermark-0.2.1-py3.7.egg\blind_watermark\bwm_core.py", line 30, in init_block_index
'最多可嵌入{}kb信息，多于水印的{}kb信息，溢出'.format(self.block_num / 1000, self.wm_size / 1000))
AssertionError: 最多可嵌入10.26kb信息，多于水印的16.384kb信息，溢出_

把图片1080X608放大一倍，变成2160X1216 则就可以正常打水印了。

请问下老哥，原图尺寸，和水印图尺寸，大小有什么要求吗？

**Comment by guofei9987** [comment]
图片像素数除以64，是最多嵌入的字节数

**Comment by cliffcrag** [comment]
> 图片像素数除以64，是最多嵌入的字节数

谢谢你的回复。但是好奇怪，我的水印图片才128*128，文件大小才2.21KB，显示占用空间也才4KB。

但是出错提示，怎么显示的是16.384kb? 见下图
![a](https://user-images.githubusercontent.com/53480428/149354366-a5c2fa06-1d94-453e-9d27-73ec11b61fd6.JPG)


另一个问题，是这个加图片水印没问题，解图片水印才出错？ 那水印加成功了吗？

**Comment by guofei9987** [comment]
解水印的时候，水印长度输入错误

**Comment by qxc190** [comment]
你好，请问为什么我解出来的空白页面加黑点在上
![wm_extracted1](https://user-images.githubusercontent.com/101338420/157671445-9b87eb28-6d8b-4515-a443-8dcac96c2c26.png)
面

**Comment by qxc190** [comment]
[](https://user-images.githubusercontent.com/101338420/157671445-9b87eb28-6d8b-4515-a443-8dcac96c2c26.png)你好，请问为什么我解出来的水印是空白页面加黑点在上
wm_extracted1
面

**Comment by qxc190** [comment]
你好，请问为什么我解出来的水印是空白页面加黑点在上
面
![wm_extracted1](https://user-images.githubusercontent.com/101338420/157672289-66987eba-e94c-413e-9040-b94a61e86f00.png)
