### ISSUE TITLE
字符串水印解码的时候出现'utf-8' codec can't decode byte 0xa7 in position问题。

### ISSUE THREAD

**Issue by cliffcrag** [guofei9987/blind_watermark#54]
在用文字加密，解密的时候，小图片加密可以正常，但是解密就出现下面的问题：

_File "D:\program\Anaconda3\lib\site-packages\blind_watermark-0.2.1-py3.7.egg\blind_watermark\blind_watermark.py", line 73, in extract
wm = bytes.fromhex(hex(int(byte, base=2))[2:]).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 13: invalid start byte_

如果是用附例的图片 ori_img.jpg 则没有问题。 同用img方法加水印，也会出现小点的图片出错。
请问下，对图片大小，有要求吗，是否可以设置小于多少象素的图片不打水印？ 自动拷贝原图或者不操作？

**Comment by guofei9987** [comment]
图片太小会自动报错。

解密失败又可能是因为传入了错误的水印长度

**Comment by cliffcrag** [comment]
> 图片太小会自动报错。
> 
> 解密失败有可能是因为传入了错误的水印长度

添加字符串水印没问题，但是解密字符串水印就出错了。
 水印长度我设的固定的，在添加的时候会显示出来，解密应该不会出错了。
