### ISSUE TITLE
解水印报错

### ISSUE THREAD

**Issue by pureZjr** [guofei9987/blind_watermark#55]
![image](https://user-images.githubusercontent.com/13707502/150710903-2d5d89be-6671-4ebd-8960-2dada0d97b33.png)

我用命令行的方式加水印 解水印，用demo没有问题的，
但是我只是将 "watermark text" 改成  "watermark textasd" ，解水印就报错了

**Comment by guofei9987** [comment]
--wm_shape 135

**Comment by pureZjr** [comment]
懂了 ，谢谢
