### ISSUE TITLE
关于截屏的attack

### ISSUE THREAD

**Issue by zhangbo** [guofei9987/blind_watermark#56]
关于截屏的attack会失败。大佬这种可以解决吗？
另外有一种跨媒介的技术，比如拍照也可以恢复，我也正在研究中。。。

**Comment by guofei9987** [comment]
截屏的例子在这里

https://github.com/guofei9987/blind_watermark/blob/417fe80ff31a4074d344897d3aa5eff7d5c3808d/examples/example_str.py#L40

拍照这个有学习资料吗？

**Comment by zhangbo** [comment]
> 
不好意思，好长时间没上github了。

**Comment by zhangbo** [comment]
https://www.dbappsecurity.com.cn/content/details284_9139.html，这个资料是之前安恒研究的。资料确实还没有找到
