### ISSUE TITLE
关于加水印之后，画质下降明显的问题

### ISSUE THREAD

**Issue by albertmenglongli** [guofei9987/blind_watermark#57]
我的照片一般10M左右 4156 × 6234，我试了demo中给的几个例子，添加水印后，画质明显下降，不知道是我哪里的参数没有设置对[![Wechat-IMG13080.jpg](https://i.postimg.cc/J4VknWhg/Wechat-IMG13080.jpg)](https://postimg.cc/rzjmn3xC)

**Comment by guofei9987** [comment]
你的原图提供一下，我跑跑看

**Comment by zhangbo** [comment]
这种是因为图片单色比较明显，所以要隐藏信息量稍大，就会让肉眼直接看出来，所以图片最好是颜色丰富一些的，从之前的fft和ifft技术，到现在的dwt和dct，都有同样的问题。

**Comment by qianjunakasumi** [comment]
信息：使用一张较为平滑的渐变图片作为输入，输出时色块分明

**Comment by albertmenglongli** [comment]
@qianjunakasumi 你的这个描述更准确，不过不知道有没有改进方法

**Comment by guofei9987** [comment]
bw.bwm_core.d1，调小这个数字即可解决，但是会降低抗攻击能力
