### ISSUE TITLE
截屏后获取水印有问题。

### ISSUE THREAD

**Issue by JauneHH** [guofei9987/blind_watermark#60]
生成水印图像后，对水印图像截屏生成新的截屏图片，截屏图片无法识别出水印，这是为什么，因为分辨率变动了吗

**Comment by jjjjjz** [comment]
我也是，截图后识别就乱码了

**Comment by guofei9987** [comment]
截图后需要反算出截图前的位置和缩放大小，代码看这里

https://github.com/guofei9987/blind_watermark/blob/d665ab71427bd7c0dba7a7a34458f15684b3460c/examples/example_str.py#L40

**Comment by jjjjjz** [comment]
好的多谢，我再看看

**Comment by ABetterCat** [comment]
这个是哪个版本的示例，最新的版本很多参数变了
