### ISSUE TITLE
关于报错AssertionError: 最多可嵌入4.096kb信息，多于水印的10.0kb信息，溢出

### ISSUE THREAD

**Issue by worshipone** [guofei9987/blind_watermark#62]
麻烦问一下，这个报错如何理解

**Comment by worshipone** [comment]
是跟图片的像素有关系吗

**Comment by worshipone** [comment]
解决了，原始图片和水印图片的像素不能差很多

**Comment by RaySue** [comment]
遇到了同样的问题，原始图片和水印图片的像素不能差很多是什么意思呢？？？

**Comment by worshipone** [comment]
> 遇到了同样的问题，原始图片和水印图片的像素不能差很多是什么意思呢？？？

意思是假如你的图片是800x800像素的，而二维码水印是400x400像素的，那就无法嵌入；
推荐图片1080x1080，二维码水印128x128

**Comment by zmou** [comment]
这个不对啊，我的原图是533x533的，水印图片：100x50，依然报错：
AssertionError: 最多可嵌入4.356kb信息，多于水印的13.275kb信息，溢出
这报错感觉牛头不对马嘴，到底是啥意思啊？
