### ISSUE TITLE
各位是否有过编解码速度测试？

### ISSUE THREAD

**Issue by FavorMylikes** [guofei9987/blind_watermark#63]
对于一个`1024x1024`的3通道图片，添加`7bits`的数据需要`3`秒encode, `2`秒decode

太慢了，各位是否有过比较全面的测试数据。

**Comment by guofei9987** [comment]
性能与图片像素的个数成线性关系。

性能改进还没太好的思路，`WaterMark(...)` 阶段可以用 `mode = 'multithreading'` 和 `mode = 'multiprocessing'` 开启多进程/多线程。并用 `processes` 来指定进程/线程数量
