### ISSUE TITLE
老哥，有没有不需要原图就能提取水印的方案

### ISSUE THREAD

**Issue by scaactk** [guofei9987/blind_watermark#7]

**Comment by guofei9987** [comment]
这个就不用原图啊

**Comment by scaactk** [comment]
我靠，试了运行，确实牛逼啊，666。。。。看了代码，，原理上还没搞太清楚，，老哥有写博客文档啥的嘛

**Comment by guofei9987** [comment]
> 我靠，试了运行，确实牛逼啊，666。。。。看了代码，，原理上还没搞太清楚，，老哥有写博客文档啥的嘛

原理没整理也没发过，知乎上写了一些介绍这个库的，但估计不是你想要的。

**Comment by BertChenJames** [comment]
> 这个就不用原图啊

攻击之后，需要知道原图大小，恢复成原图才行，不然提取水印是错的，请问这个问题咋解决啊？
