### ISSUE TITLE
AssertionError: 最多可嵌入10.375kb信息，多于水印的45.0kb信息，溢出

### ISSUE THREAD

**Issue by huxiuhang** [guofei9987/blind_watermark#8]
老哥小白一枚，我想问下这个标准是什么

**Comment by guofei9987** [comment]
大概1比16

**Comment by huxiuhang** [comment]
原图大小要是水印的16倍是吗

**Comment by huxiuhang** [comment]
感谢大佬，我再摸索一下

**Comment by huxiuhang** [comment]
我测试的水印是png,6.54KB,原图是128.2kb，依然输出这个报错，是对图片有其他要求吗

**Comment by huxiuhang** [comment]
大佬确实不行，水印1.89kb，原图283.91kb。还是报错AssertionError: 最多可嵌入3.9kb信息，多于水印的45.0kb信息，溢出

**Comment by guofei9987** [comment]
> 大佬确实不行，水印1.89kb，原图283.91kb。还是报错AssertionError: 最多可嵌入3.9kb信息，多于水印的45.0kb信息，溢出

按照分辨率计算，1:16，减少一下分辨率试试
