### ISSUE TITLE
我用pyQt5增加了一个加解暗水印的操作界面

### ISSUE THREAD

**Issue by pan2za** [guofei9987/blind_watermark#84]
https://e.coding.net/goodput/desktop-watermark/blind_watermark.git

主要增加了UI的一个界面

使用pyQT5写的

主要问题是：有些时候水印内容太多，或者有特殊字符，例如空格，逗号就无法解析。应该是程序问题，和UI无关。

**Comment by guofei9987** [comment]
That is COOL! But I cannot open the link.

**Comment by pan2za** [comment]
fyi:
https://github.com/pan2za/blind_watermark.git
