### ISSUE TITLE
嵌入水印后的图片 文件有点大 & 信噪比有点高

### ISSUE THREAD

**Issue by weweus** [guofei9987/blind_watermark#90]
将字符串水印嵌入一张高清图（1440x2560）后，发现文件大小从2780KB增加到了10821K。并且与原图比较，肉眼可见有噪声。
是我参数没调好么？大家有什么解决办法么？

**Comment by guofei9987** [comment]
有个 `compression_ratio` 参数可以控制嵌入后的大小
