### ISSUE TITLE
截图后解码失败

### ISSUE THREAD

**Issue by hjing100** [guofei9987/blind_watermark#94]
代码：
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# embed string
import numpy as np
from blind_watermark import WaterMark
from blind_watermark import att
from blind_watermark.recover import estimate_crop_parameters, recover_crop
import cv2
import os
import time

start_time=time.time()

# os.chdir(os.path.dirname(__file__))

bwm = WaterMark(password_img=1, password_wm=1)
# bwm.read_img('examples/pic/ori_img.jpeg')
bwm.read_img('examples/pic-test/NI7A7780_1.JPG')
# wm = '@guofei9987 开源万岁！'
wm = 'hello world.My name is xiaoming,my phone is 1237868765456'
# wm = 'My name is xiaoming,my phone is 1237868765456'
bwm.read_wm(wm, mode='str')
# bwm.embed('examples/output/embedded.png')

len_wm = len(bwm.wm_bit)  # 解水印需要用到长度
print('Put down the length of wm_bit {len_wm}'.format(len_wm=len_wm))

# ori_img_shape = cv2.imread('examples/pic/ori_img.jpeg').shape[:2]  # 抗攻击有时需要知道原图的shape
ori_img_shape = cv2.imread('examples/pic-test/NI7A7780_1.JPG').shape[:2]

# %% 解水印
bwm1 = WaterMark(password_img=1, password_wm=1)
wm_extract = bwm1.extract('examples/output/embedded.png', wm_shape=len_wm, mode='str')
print("不攻击的提取结果：", wm_extract)

try:
    assert wm == wm_extract, '不攻击 提取水印和原水印不一致'
except AssertionError:
    print('不攻击 提取水印和原水印不一致')

# %% 截屏攻击 = 剪切攻击 + 缩放攻击 + 不知道攻击参数
# loc_r = ((0.1, 0.1), (0.7, 0.6))
# scale = 0.7
# _, (x1, y1, x2, y2) = att.cut_att2(input_filename='examples/output/embedded.png', output_file_name='examples/output/jieping2.png',
#                                    loc_r=loc_r, scale=scale)
# print(f'Crop attack\'s real parameters: x1={x1},y1={y1},x2={x2},y2={y2}')

# estimate crop attack parameters:
# original_file='examples/output/embedded.png'
# template_file='examples/output/jieping2.png',
(x1, y1, x2, y2), image_o_shape, score, scale_infer = estimate_crop_parameters(original_file='examples/pic-test/NI7A7780_1.JPG',
                                                                               template_file='examples/output/cut.png',
                                                                               scale=(0.5, 2), search_num=200)

print(f'Crop attack\'s estimate parameters: x1={x1},y1={y1},x2={x2},y2={y2}. score={score}')

# recover from attack:
recover_crop(template_file='examples/output/cut.png', output_file_name='examples/output/jieping2_huanyuan.png',
             loc=(x1, y1, x2, y2), image_o_shape=image_o_shape)

bwm1 = WaterMark(password_wm=1, password_img=1)
wm_extract = bwm1.extract('examples/output/jieping2_huanyuan.png', wm_shape=len_wm, mode='str')
print("截屏攻击，不知道攻击参数。提取结果：", wm_extract)
try:
    assert wm == wm_extract, '截屏攻击，不知道攻击参数 提取水印和原水印不一致'
except AssertionError:
    print('截屏攻击，不知道攻击参数 提取水印和原水印不一致')

说明：
cut.png是我基于电脑版微信截图得到的结果，
NI7A7780_1.JPG像素值大小是3840*5760
cut.png像素值大小是498*950  (但是，我只截图掉了一点周边。像素值确减少了很多)

结果：
攻击的提取结果： hello world.My name is xiaoming,my phone is 1237868765456
Crop attack's estimate parameters: x1=2387,y1=621,x2=2636,y2=1096. score=0.3878258764743805
截屏攻击，不知道攻击参数。提取结果： `�,^gHq��A� %��_�HX6� As�TG��N� �Ε �}`��p(@4��
截屏攻击，不知道攻击参数 提取水印和原水印不一致

**Comment by hjing100** [comment]
**
你好
**

**Comment by hjing100** [comment]
**
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# embed string
import numpy as np
from blind_watermark import WaterMark
from blind_watermark import att
from blind_watermark.recover import estimate_crop_parameters, recover_crop
import cv2
import os
import time

start_time=time.time()

# os.chdir(os.path.dirname(__file__))

bwm = WaterMark(password_img=1, password_wm=1)
# bwm.read_img('examples/pic/ori_img.jpeg')
bwm.read_img('examples/pic-test/NI7A7780_1.JPG')
# wm = '@guofei9987 开源万岁！'
wm = 'hello world.My name is xiaoming,my phone is 1237868765456'
# wm = 'My name is xiaoming,my phone is 1237868765456'
bwm.read_wm(wm, mode='str')
bwm.embed('examples/output/embedded.png')

len_wm = len(bwm.wm_bit)  # 解水印需要用到长度
print('Put down the length of wm_bit {len_wm}'.format(len_wm=len_wm))

# ori_img_shape = cv2.imread('examples/pic/ori_img.jpeg').shape[:2]  # 抗攻击有时需要知道原图的shape
ori_img_shape = cv2.imread('examples/pic-test/NI7A7780_1.JPG').shape[:2]

# %% 解水印
bwm1 = WaterMark(password_img=1, password_wm=1)
wm_extract = bwm1.extract('examples/output/embedded.png', wm_shape=len_wm, mode='str')
print("不攻击的提取结果：", wm_extract)

try:
    assert wm == wm_extract, '不攻击 提取水印和原水印不一致'
except AssertionError:
    print('不攻击 提取水印和原水印不一致')


# %% 截屏攻击 = 剪切攻击 + 缩放攻击 + 不知道攻击参数
# loc_r = ((0.1, 0.1), (0.7, 0.6))
# scale = 0.7
# _, (x1, y1, x2, y2) = att.cut_att2(input_filename='examples/output/embedded.png', output_file_name='examples/output/jieping2.png',
#                                    loc_r=loc_r, scale=scale)
# print(f'Crop attack\'s real parameters: x1={x1},y1={y1},x2={x2},y2={y2}')

# estimate crop attack parameters:
# template_file='examples/output/jieping2.png',
(x1, y1, x2, y2), image_o_shape, score, scale_infer = estimate_crop_parameters(original_file='examples/output/embedded.png',
                                                                               template_file='examples/output/cut.png',
                                                                               scale=(0.5, 2), search_num=200)

print(f'Crop attack\'s estimate parameters: x1={x1},y1={y1},x2={x2},y2={y2}. score={score}')

# recover from attack:
recover_crop(template_file='examples/output/cut.png', output_file_name='examples/output/jieping2_huanyuan.png',
             loc=(x1, y1, x2, y2), image_o_shape=image_o_shape)

bwm1 = WaterMark(password_wm=1, password_img=1)
wm_extract = bwm1.extract('examples/output/jieping2_huanyuan.png', wm_shape=len_wm, mode='str')
print("截屏攻击，不知道攻击参数。提取结果：", wm_extract)
try:
    assert wm == wm_extract, '截屏攻击，不知道攻击参数 提取水印和原水印不一致'
except AssertionError:
    print('截屏攻击，不知道攻击参数 提取水印和原水印不一致')





**

**Comment by hjing100** [comment]
代码：

import numpy as np
from blind_watermark import WaterMark
from blind_watermark import att
from blind_watermark.recover import estimate_crop_parameters, recover_crop
import cv2
import os
import time

start_time=time.time()


bwm = WaterMark(password_img=1, password_wm=1)

bwm.read_img('examples/pic-test/NI7A7780_1.JPG')
wm = 'hello world.My name is xiaoming,my phone is 1237868765456'
bwm.read_wm(wm, mode='str')
bwm.embed('examples/output/embedded.png')

len_wm = len(bwm.wm_bit)  
print('Put down the length of wm_bit {len_wm}'.format(len_wm=len_wm))

ori_img_shape = cv2.imread('examples/pic-test/NI7A7780_1.JPG').shape[:2]


bwm1 = WaterMark(password_img=1, password_wm=1)
wm_extract = bwm1.extract('examples/output/embedded.png', wm_shape=len_wm, mode='str')
print("不攻击的提取结果：", wm_extract)

try:
    assert wm == wm_extract, '不攻击 提取水印和原水印不一致'
except AssertionError:
    print('不攻击 提取水印和原水印不一致')


(x1, y1, x2, y2), image_o_shape, score, scale_infer = estimate_crop_parameters(original_file='examples/output/embedded.png',
                                                                               template_file='examples/output/cut.png',
                                                                               scale=(0.5, 2), search_num=200)

print(f'Crop attack\'s estimate parameters: x1={x1},y1={y1},x2={x2},y2={y2}. score={score}')

recover_crop(template_file='examples/output/cut.png', output_file_name='examples/output/jieping2_huanyuan.png',
             loc=(x1, y1, x2, y2), image_o_shape=image_o_shape)

bwm1 = WaterMark(password_wm=1, password_img=1)
wm_extract = bwm1.extract('examples/output/jieping2_huanyuan.png', wm_shape=len_wm, mode='str')
print("截屏攻击，不知道攻击参数。提取结果：", wm_extract)
try:
    assert wm == wm_extract, '截屏攻击，不知道攻击参数 提取水印和原水印不一致'
except AssertionError:
    print('截屏攻击，不知道攻击参数 提取水印和原水印不一致')

**Comment by guofei9987** [comment]
https://github.com/guofei9987/blind_watermark/issues/81#issuecomment-1288355604
