### ISSUE TITLE
不提供原图提取水印是失败的，代码里面是这样实现的，它要传入一个 len_wm，再看len_wm 是怎么生成的，代码是用的 水印字符串 来做计算的，也就是不提供原图，至少要提供 水印字符串的长度，或者是直接提供  水印字符串 ，这就矛盾了？

### ISSUE THREAD

**Issue by liuweizhou** [guofei9987/blind_watermark#96]
bwm1 = WaterMark(password_img=1, password_wm=1)
wm_extract = bwm1.extract('output/embedded.png', wm_shape=len_wm, mode='str')
print(wm_extract)

提取 被加过水印的图片 只少要知道 len_wm， 除非就是你添加水印的时候把 添加完水印的文件 和  len_wm 一起保存。

但是你在看 len_wm  的生成原理      len_wm = len(bwm1.wm_bit) ，那也就是看一下 wm_bit 是怎么生辰的。
    def read_wm(self, wm_content, mode='img'):
        assert mode in ('img', 'str', 'bit'), "mode in ('img','str','bit')"
        if mode == 'img':
            wm = cv2.imread(filename=wm_content, flags=cv2.IMREAD_GRAYSCALE)
            assert wm is not None, 'file "{filename}" not read'.format(filename=wm_content)

            # 读入图片格式的水印，并转为一维 bit 格式，抛弃灰度级别
            self.wm_bit = wm.flatten() > 128

        elif mode == 'str':
            byte = bin(int(wm_content.encode('utf-8').hex(), base=16))[2:]
            self.wm_bit = (np.array(list(byte)) == '1')
        else:
            self.wm_bit = np.array(wm_content)

**Comment by guofei9987** [comment]
你可以把水印统一做成长度 64 的

**Comment by liuweizhou** [comment]
我试试，好的，谢谢



在 2022-12-01 20:50:19，"郭飞" ***@***.***> 写道：

Closed #96 as completed.

**Comment by KDreamelf** [comment]
可以将长度在加密完成后输出出来。最好不要一起公布长度。这部分的长度由作者保存（相当于某种程度上的私钥）。这样也能最大限度的防止同模攻击（毕竟你项目是开源的，我也打算将我的加密脚本公开以便广大画师维权）

**Comment by KDreamelf** [comment]
/usr/local/bin/python3'  '/Users/zhangtianhua/Documents/图片暗水印/图片暗水印.py'  && echo Exit status: $? && exit 1

    图片隐写加密工具
    作者：天使
    本工具可将图片打上肉眼不可见的暗水印。
    当发生版权纠纷时，可作为证据
    对方拿着带暗水印的图到处乱跑的话，直接秒了。
    打击赛博人贩子人人有责。
    建议这样打水印：
    版权所有，盗图必究。作者圈名：天使，QQ：1622219669，本图仅授权给自己，不存在任何商业出售的可能。
    =====================
    
请选择模式：1（或者直接回车）=加密（写入），2=解密（读取）2
将图片拖入此处>>/Users/zhangtianhua/Pictures/言七画作/代表作，封面作，定价作/7BC4A91529A2175F7B160C24EFCA8786.png 
请提供隐写数据长度（整数）：***
解码结果：****
按回车结束程序。
