### ISSUE TITLE
使用命令行提取水印时报错

### ISSUE THREAD

**Issue by AAAAAAAAAAAASada** [guofei9987/blind_watermark#99]

**Comment by AAAAAAAAAAAASada** [comment]
暂时解决, numpy版本问题[https://github.com/WongKinYiu/yolov7/issues/1280#issuecomment-1360917977](url)
希望针对numpy==1.24.0进行更新

**Comment by guofei9987** [comment]
Thank you! bug fixed in version 0.4.4

**Comment by AAAAAAAAAAAASada** [comment]
It's glad to see this project is still maintained.
